// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salon.Data;

#nullable disable

namespace salon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129090408_AddProductsTable")]
    partial class AddProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Salon.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Service",
                            Description = "Basic haircut with style.",
                            Name = "Classic Haircut",
                            Price = 30m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Service",
                            Description = "Deep nourishment for hair.",
                            Name = "Hair Spa Treatment",
                            Price = 60m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Retail",
                            Description = "Premium shampoo for smooth hair.",
                            Name = "Argan Oil Shampoo",
                            Price = 25m
                        });
                });

            modelBuilder.Entity("Salon.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "50% off all haircuts – one day only!",
                            Title = "Black Friday Sale"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Haircut + Facial in a combo price for the weekend.",
                            Title = "Combo Offer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "20% off on the first visit of any new customer.",
                            Title = "New Customer Special"
                        });
                });

            modelBuilder.Entity("Salon.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "password1",
                            StaffId = "staff1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "password2",
                            StaffId = "staff2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
